### ISSUE TITLE
bug: unsupported operand type error when running wait_for functions

### ISSUE THREAD

**Issue by iromli** [GluuFederation/pygluu-containerlib#33]
Using latest `backoff` library (v2.1.0 per this issue) throws the following error:

```
Traceback (most recent call last):
  File "/app/scripts/wait.py", line 40, in <module>
    main()
  File "/app/scripts/wait.py", line 36, in main
    wait_for(manager, deps)
  File "/usr/lib/python3.10/site-packages/pygluu/containerlib/wait.py", line 435, in wait_for
    callback["func"](manager, **callback["kwargs"])
  File "/usr/lib/python3.10/site-packages/backoff/_sync.py", line 117, in retry
    seconds = _next_wait(wait, e, jitter, elapsed, max_time)
  File "/usr/lib/python3.10/site-packages/backoff/_common.py", line 54, in _next_wait
    seconds = min(seconds, max_time - elapsed)
TypeError: unsupported operand type(s) for -: 'function' and 'float'
```

The error occurs when conditions of `wait_for` functions are not met, i.e. checking availability of MySQL.

**Comment by iromli** [comment]
Fixed in e870cfff7f23a61bb804d3d91fa6ef2d271a03fc
